In [2]:
!pip install keras


In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import io

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from sklearn.model_selection import train_test_split
import seaborn as sns

In [4]:
import keras
from keras.models import  Sequential
from keras.layers import  Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [0]:
import pydot
import graphviz
# from Ipython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model





In [8]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving iris.csv to iris.csv
User uploaded file "iris.csv" with length 3858 bytes


In [0]:
df = pd.read_csv(io.StringIO(uploaded['iris.csv'].decode('utf-8')))

In [10]:
df.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
X= df.iloc[:,0:4]
y= df.iloc[:,4]

In [0]:
#Label Encoding k lia
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

y1=encoder.fit_transform(y)
Y=pd.get_dummies(y1).values


In [0]:

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)


In [17]:
X_train


sepal_length  sepal_width  petal_length  petal_width
99            5.7          2.8           4.1          1.3
133           6.3          2.8           5.1          1.5
127           6.1          3.0           4.9          1.8
37            4.9          3.1           1.5          0.1
56            6.3          3.3           4.7          1.6
..            ...          ...           ...          ...
29            4.7          3.2           1.6          0.2
19            5.1          3.8           1.5          0.3
126           6.2          2.8           4.8          1.8
33            5.5          4.2           1.4          0.2
78            6.0          2.9           4.5          1.5

[120 rows x 4 columns]

In [19]:
model=Sequential()
model.add(Dense(4,input_shape=(4,),activation='relu'))

#Layer2 for Output or yahan 3 islia likha ha q k 0 1 ya pher 2 mein se koi 1 ai ga ans
model.add(Dense(3,activation='softmax'))


In [20]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [21]:
model.fit(X_train,y_train, batch_size=10, epochs=100)


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/100





120/120 [==============================] - 1s 5ms/step - loss: 1.3970 - acc: 0.0167
Epoch 2/100
120/120 [==============================] - 0s 157us/step - loss: 1.3348 - acc: 0.1250
Epoch 3/100
120/120 [==============================] - 0s 145us/step - loss: 1.2851 - acc: 0.1833
Epoch 4/100
120/120 [==============================] - 0s 180us/step - loss: 1.2427 - acc: 0.2167
Epoch 5/100
120/120 [==============================] - 0s 154us/step - loss: 1.2077 - acc: 0.2417
Epoch 6/100
120/120 [==============================] - 0s 178us/step - loss: 1.1787 - acc: 0.2500
Epoch 7/100
120/120 [==============================] - 0s 136us/step - loss: 1.1530 - acc: 0.2667
Epoch 8/100
120/120 [==============================] - 0s 140us/step - loss: 1.1318 - acc: 0.2833
Epoch 9/100
120/120 [==============================] - 0s 139us/step - loss: 1.1153 - acc: 0.2917
Epoch 10/100
120/1

In [0]:
y_pred= model.predict(X_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)


In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.54      0.70        13
           2       0.65      1.00      0.79        11

    accuracy                           0.80        30
   macro avg       0.88      0.85      0.83        30
weighted avg       0.87      0.80      0.79        30

[[ 6  0  0]
 [ 0  7  6]
 [ 0  0 11]]


In [25]:
#total accuracy
(6+7+11)/30

0.8